/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{vue,js,ts,jsx,tsx}",
    "./components/**/*.{vue,js,ts,jsx,tsx}",
    "./layouts/**/*.{vue,js,ts,jsx,tsx}",
    "./pages/**/*.{vue,js,ts,jsx,tsx}",
    "./plugins/**/*.{vue,js,ts,jsx,tsx}",
    "./utils/**/*.{vue,js,ts,jsx,tsx}",
    "./nuxt.config.{js,ts}",
    "./app.vue"
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#3b6934",
        "on-error-container": "#93000a",
        "background": "#faf9f6",
        "secondary-container": "#fd8867",
        "primary": "#154212",
        "tertiary-container": "#7c4004",
        "surface-dim": "#dbdad7",
        "secondary": "#9f4026",
        "on-tertiary-fixed": "#2f1400",
        "primary-container": "#2d5a27",
        "on-primary-container": "#9dd090",
        "on-secondary-container": "#732108",
        "on-primary-fixed-variant": "#23501e",
        "error": "#ba1a1a",
        "surface": "#faf9f6",
        "on-secondary-fixed": "#3b0900",
        "surface-variant": "#e3e2e0",
        "surface-container-low": "#f4f3f1",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#002201",
        "tertiary-fixed-dim": "#ffb780",
        "on-tertiary-fixed-variant": "#6f3800",
        "on-surface": "#1a1c1a",
        "surface-bright": "#faf9f6",
        "secondary-fixed": "#ffdbd1",
        "primary-fixed": "#bcf0ae",
        "surface-container": "#efeeeb",
        "on-background": "#1a1c1a",
        "inverse-primary": "#a1d494",
        "outline-variant": "#c2c9bb",
        "on-tertiary-container": "#ffb175",
        "tertiary-fixed": "#ffdcc4",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f312f",
        "secondary-fixed-dim": "#ffb5a1",
        "surface-container-highest": "#e3e2e0",
        "outline": "#72796e",
        "on-secondary-fixed-variant": "#802a11",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary": "#5b2d00",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e9e8e5",
        "on-primary": "#ffffff",
        "on-surface-variant": "#42493e",
        "primary-fixed-dim": "#a1d494",
        "inverse-on-surface": "#f2f1ee",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "gutter": "24px",
        "unit": "8px",
        "margin-desktop": "64px",
        "container-max": "1280px"
      },
      fontFamily: {
        display: ["Bangers", "cursive"],
        sans: ["DM Sans", "sans-serif"],
        "display-lg-mobile": ["Bangers", "cursive"],
        "headline-lg": ["Bangers", "cursive"],
        "body-md": ["DM Sans", "sans-serif"],
        "headline-md": ["Bangers", "cursive"],
        "display-lg": ["Bangers", "cursive"],
        "body-lg": ["DM Sans", "sans-serif"],
        "label-sm": ["DM Sans", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["40px", { lineHeight: "46px", fontWeight: "400", letterSpacing: "0.04em" }],
        "headline-lg": ["32px", { lineHeight: "38px", fontWeight: "400", letterSpacing: "0.04em" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "30px", fontWeight: "400", letterSpacing: "0.04em" }],
        "display-lg": ["56px", { lineHeight: "62px", letterSpacing: "0.05em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
